server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '123456'
    url: jdbc:mysql://localhost:3306/test_forge?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
  jackson:
    date-format: yyyy-MM-dd
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000
mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"